package io.github.jristretto.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Specify a default value for a field.
 *
 * @author Pieter van den Hombergh  {@code pieter.van.den.hombergh@gmail.com}
 */
@Retention(RetentionPolicy.RUNTIME)
@Target( { ElementType.FIELD, ElementType.RECORD_COMPONENT, ElementType.METHOD } )
public @interface Default {
    /**
     * Is the ID generated by the persistence layer.
     * @return true by default, not if set as parameter
     */
    String value() default "";
    boolean generated() default true;
}
